accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.Register.as_view(), name='register'),
]

pollapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from pollapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('polls/', include('polls.urls', namespace="polls")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('social/', include('social_django.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('list/', views.polls_list, name='list'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.endpoll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/', views.choice_delete, name='choice_delete'),
    path('<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
]

templates/includes/footer.html
<footer class="page-footer font-small bg-dark text-white fixed-bottom">
    <div class= "footer-copyright text-center py-3">&copy: 2024 Copyright:
        <a herf="https://localhost:8000">PollApp</a>
    </div>
  </footer>

templates/includes/navbar.html
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between">
        <a class="navbar-brand mr-4" id="site" href="{%  url 'home' %}"></a>
        <form class="form-inline">
            <a class="btn btn-outline-primary "
             href="{%  url 'home' %}"><i>PK</i></a>
        </form>
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class= "nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}"
                         href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'list' %}active{% endif %}" 
                             href="{% url 'polls:list' %}">Polls</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle nav-link {% if request.resolver_match.url_name == '#' %}active{% endif %}"
                             href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                 Dropdown
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a> 
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                        </li>
                    {% endif %}
                </div>
                <form class="form-inline ">
                    
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-primary mr-5" type="submit">Search</button>
                </form>
            
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'list_by_user' %}active{% endif %}"
                         href="{% url 'polls:list_by_user' %}">My Polls</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'logout' %}active{% endif %}"
                         href="{% url 'accounts:logout' %}">Logout</a>
                    </li>

                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'login' %}active{% endif %}"
                         href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'register' %}active{% endif %}"
                         href="{% url 'accounts:register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        
    </nav>
</header>